use_frameworks!

target 'SineWaveView_Example' do
  pod 'SineWaveView', :path => '../'

  target 'SineWaveView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
